#pragma once

enum Transitions {
	RECEIVED_DATA_WAKE_UP,
	RECEIVED_SCREENSHOT_WAKE_UP,
	RECEIVED_REQUEST_PACKET,
	RECEIVED_VARIABLE_DESCRIPTION_PACKET,
	RECEIVED_SCREENSHOT_REQUEST,
	RECEIVED_ACK,
	RECEIVED_VALUE_PACKET,
	RECEIVED_SCREENSHOT_DATA,
	RECEIVED_END_PACKET,
	SENT_END_PACKET
};